# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /api/category.:sf_format
  class: sfDoctrineRoute
  param: { module: category, action: index }
  options: { model: Category, type: list }
  requirements:
    sf_format: (?:json)

product:
  url: /api/product.:sf_format/:id
  class: sfDoctrineRoute
  param: { module: product, action: index }
  options: { model: Category, type: list }
  requirements:
    sf_format: (?:json)
    id: \d+
    
table_order:
  url: /api/order
  class: sfDoctrineRoute
  param: { module: table_order, action: index }
  options: { model: TableOrder, type: object }
  requirements:
    sf_method: post
  
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
