<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }
    
    public function getProducts($id) {
       $q = Doctrine_Query::create()
               ->from('Product p')
               ->where('p.category_id = ?', $id);
       return $q->execute();
   }
   
   public function getCategoryInArray() {
       $categorys = Doctrine_Core::getTable('Category')
               ->createQuery('a')
               ->execute();
       $categorys_array = array();
       $i = 0;
       foreach ($categorys as $category) {
           $categorys_array[$i] = array(
             'id' => $category->getId(),
             'name' => $category->getName()
           );
           $i++;
       }
       return $categorys_array;
   }
}