<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }
    
    public function getProducts($id) {
       $q = Doctrine_Query::create()
               ->from('Product p')
               ->where('p.category_id = ?', $id);
       return $q->execute();
   }
   
   public function getJSONArray() {
       $categorys = Doctrine_Core::getTable('Category')
               ->createQuery('a')
               ->execute();
       $categorys_array = array();
       $i = 0;
       foreach ($categorys as $category) {
           $products = Doctrine_Core::getTable('Category')->getProducts($category->getId());
           $products_array = array();
           $j = 0;
           foreach ($products as $product) {
               $product_array[$j] = array(
                   'id' => $product->getId(),
                   'name' => $product->getName(),
                   'price' => $product->getPrice(),
                   'description' => $product->getDescription()
               );
               $j++;
           }
           $categorys_array[$i] = array(
             'id' => $category->getId(),
             'name' => $category->getName(),
             'product' => $product_array
           );
           $i++;
       }
       return $categorys_array;
   }
}