<?php

/**
 * DiningRoomTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiningRoomTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiningRoomTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiningRoom');
    }
    
    public function getDiningTables($id) {
       $q = Doctrine_Query::create()
               ->from('DiningTable d')
               ->where('d.dining_room_id = ?', $id);
       return $q->execute();
   }
}