<?php

/**
 * MenuProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MenuProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MenuProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MenuProduct');
    }
}