<?php

/**
 * MenuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MenuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MenuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Menu');
    }
    
    public function getJSONArray() {
       $menu = Doctrine::getTable('Menu')->findOneBy('is_available', true);
       if($menu) {
            $menu_products = Doctrine::getTable('MenuProduct')->findBy('menu_id', $menu->getId());
            $category_array = array();
            foreach ($menu_products as $menu_product) {
                if($menu_product->getIsAvailable()) {
                        $product = array(
                            "id" => $menu_product->getProduct()->getId(),
                            "name" => $menu_product->getProduct()->getName(), 
                            "price" => $menu_product->getProduct()->getPrice(),
                            "description" => $menu_product->getProduct()->getDescription()
                        );
                        $category = $menu_product->getProduct()->getCategory();
                        if(!in_array(array("id" => $category->getId()), $category_array)) {
                            array_push($category_array, array(
                                "id" => $category->getId(),
                                "name" => $category->getName(),
                                "product" => array($product)
                            ));
                        }
                        else {
                            $product_arrays = $category_array[$category->getId()];
                            array_push($product, $product_arrays["product"]);
                        }
                }

            }

            return array("category" => $category_array);
       }
       else {
           return array();
       }
   }
}