<?php

/**
 * OrderProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrderProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrderProduct');
    }
}