<?php

/**
 * Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    youfood
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product extends BaseProduct
{
    public function delete(Doctrine_Connection $conn = null)
    {
        unlink(sfConfig::get('sf_upload_dir').'/products/'.$this->getImage());
        return parent::delete($conn);
    }
    
    public function save(Doctrine_Connection $conn = null) {
        parent::save($conn);
        if($this->getImage()) {
            $thumbnail = new sfThumbnail(133, 100);
            $thumbnail->loadFile(sfConfig::get('sf_upload_dir').'/products/'.$this->getImage());
            $thumbnail->save(sfConfig::get('sf_upload_dir').'/products/thumbnails/'.$this->getImage());
        }
    }
}
