<?php

/**
 * TabletTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TabletTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TabletTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tablet');
    }
    
    public function getTablet()
    {
        return $this->createQuery('p');
    }
    
    public function getTabletByAndroidId($android_id)
    {
        $p = $this->getTablet()
                ->where('p.android_id = ?', $android_id)
                ->limit(1);
        
        return $p;
    }
    
    public function getHelpRequestByWaiter($waiter_id)
    {
        $p = $this->getTablet()
                ->leftJoin('p.DiningTable d')
                ->leftJoin('d.DiningRoom r')
                ->where('r.waiter_id = ?', $waiter_id)
                ->andWhere('p.help = 1');
        return $p;
    }
}