<?php

/**
 * TabletRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TabletRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TabletRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TabletRequest');
    }
}