<?php

/**
 * TableOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TableOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TableOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TableOrder');
    }
}