<?php

/**
 * TableOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TableOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TableOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TableOrder');
    }
    
    public function getUnclosed() {
       $q = Doctrine_Query::create()
               ->from('TableOrder t')
               ->where('t.is_closed = 0');
       return $q->execute();
   }
}