<?php

/**
 * TabletTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TabletTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TabletTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tablet');
    }
}