<?php

/**
 * TableOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TableOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TableOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TableOrder');
    }
    
    public function getUnclosedByWaiter($waiter_id) {
       $q = $this->createQuery('t')
               ->select('t.*')
               ->leftJoin('t.DiningTable d')
               ->leftJoin('d.DiningRoom r')
               ->where('r.waiter_id = ?', $waiter_id)
               ->andWhere('t.is_closed = 0');
       return $q;
   }
   
   public function getByWaiter($waiter_id) {
       $q = $this->createQuery('t')
               ->leftJoin('t.DiningTable d')
               ->leftJoin('d.DiningRoom r')
               ->where('r.waiter_id = ?', $waiter_id);
       return $q;
   }
   
   
}