<?php

/**
 * TableOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    youfood
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TableOrder extends BaseTableOrder
{
    public function save(Doctrine_Connection $conn = null)
    {
        if ($this->isNew() && !$this->getCreatedAt())
        {
            $this->setCreatedAt(time());
        }
 
        return parent::save($conn);
    }
    
    public function getTotalPrice() {
        $price = 0.00;
        foreach ($this->getOrderProduct() as $order_product) {
            $price += $order_product->getProduct()->getPrice() * $order_product->getQuantity();
        }
        return $price;
    }
}
