<?php

/**
 * ZoneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZoneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZoneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Zone');
    }
    
    public function getDiningRooms($id) {
       $q = Doctrine_Query::create()
               ->from('DiningRoom d')
               ->where('d.zone_id = ?', $id);
       return $q->execute();
   }
}