# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

#help

help_list:
  url: /help/list
  class: sfDoctrineRoute
  param: { module: help_request, action: list, sf_format: json }
  options: { model: Tablet, type: list }
  requirements: 
    sf_method: get
  
help_list_change:
  url: /help/list
  class: sfDoctrineRoute
  param: { module: help_request, action: list }
  options: { model: Tablet, type: list }
  requirements: 
    sf_method: post
    
#stats
stats_zone:
  url: /stats/zone/:id
  class: sfDoctrineRoute
  options: { model: Zone, type: object }
  param: { module: stats, action: zone }
  requirements:
    id: \d+
    sf_method: post

stats:
  url: /stats
  class: sfRoute
  param: { module: stats, action: index }
  
#menu
menu:
  class: sfDoctrineRouteCollection
  options: { model: Menu, prefix_path: /menu }
  
main_menu:
  url: /menu/main/:id
  class: sfDoctrineRoute
  options: { model: Menu, type: object }
  param: { module: menu, action: updateMain }
  requirements:
    id: \d+
    sf_method: put
    
menu_detail:
  url: /menu/detail/:id
  class: sfDoctrineRoute
  options: { model: Menu, type: object }
  param: { module: menu_product, action: index }
  requirements:
    id: \d+
  
#menu_product
menu_product_new:
  url: /menu/detail/new/:id
  class: sfDoctrineRoute
  options: { model: Menu, type: object }
  param: { module: menu_product, action: new }
  requirements:
    id: \d+

menu_product_create:
  url: /menu/detail/create
  class: sfDoctrineRoute
  options: { model: Menu, type: object }
  param: { module: menu_product, action: create }
  requirements:
    id: \d+
    sf_method: post
    
menu_product_delete:
  url: /menu/detail/delete/:id
  class: sfDoctrineRoute
  options: { model: MenuProdut, type: object }
  param: { module: menu_product, action: delete }
  requirements:
    id: \d+
    sf_method: delete
    
menu_product_available:
  url: /menu/detail/available/:id
  class: sfDoctrineRoute
  options: { model: MenuProdut, type: object }
  param: { module: menu_product, action: available }
  requirements:
    id: \d+
    sf_method: put
#tablet
tablet_request:
  url: /tablet/request
  class: sfRoute
  param: { module: tablet, action: request }

tablet:
  url: /tablet/associated
  class: sfRoute
  param: { module: tablet, action: associated }
  
tablet_association:
  url: /tablet/association
  class: sfRoute
  param: { module: tablet, action: association }
  requirements: { sf_method: post }
  
tablet_remove:
  url: /tablet/remove/:android_id
  class: sfDoctrineRoute
  options: { model: Tablet, type: object }
  param: { module: tablet, action: remove }
  requirements: { android_id: \w+ }
  
tablet_request_gritter:
  url: /tablet/request.:sf_format
  class: sfDoctrineRoute
  options: { model: TabletRequest, type: list }
  param: { module: tablet, action: ajax }
  requirements:
    sf_format: (?:json)
    sf_method: get
    
tablet_request_gritter_close:
  url: /tablet/request.:sf_format
  class: sfDoctrineRoute
  options: { model: TabletRequest, type: list }
  param: { module: tablet, action: closeNew }
  requirements:
    sf_format: (?:json)
    sf_method: post
  
#table_order
  
table_order:
  url: /order
  class: sfDoctrineRoute
  options: { model: TableOrder, type: object }
  param: { module: table_order, action: index }

table_order_ajax:
  url: /order/list.:sf_format
  class: sfDoctrineRoute
  options: { model: TableOrder, type: object }
  param: { module: table_order, action: ajax, sf_format: html }
  requirements: { sf_format:  (?:html|js)}

table_order_news:
  url: /order/news.:sf_format
  class: sfDoctrineRoute
  options: { model: TableOrder, type: list }
  param: { module: table_order, action: getNew }
  requirements: { sf_format: (?:json), sf_method: get}
  
table_order_news_close:
  url: /order/news.:sf_format
  class: sfDoctrineRoute
  options: { model: TableOrder, type: list }
  param: { module: table_order, action: closeNew }
  requirements: { sf_format: (?:json), sf_method: post}
  
table_order_detail_click:
  url: /order/new/detail/:id
  class: sfDoctrineRoute
  options: { model: TableOrder, type: object }
  params: { module: table_order, action: clickDetail }
  requirements: { id: \d+ }
  
table_order_detail:
  url: /order/detail/:id
  class: sfDoctrineRoute
  options: { model: TableOrder, type: object }
  params: { module: order_product, action: index }
  requirements: { id: \d+ }
  
table_order_close:
  url: /order/close/:id/:all
  class: sfDoctrineRoute
  options: { model: TableOrder, type: object }
  params: { module: table_order, action: close }
  requirements: { id: \d+ }
  
table_order_all:
  url: /order/:all
  class: sfDoctrineRoute
  options: { model: TableOrder, type: object }
  param: { module: table_order, action: index }
#order_product

#zone 
zone:
  class: sfDoctrineRouteCollection
  options: { model: Zone }

zone_detail:
  url:  /zone/room/:id
  class: sfDoctrineRoute
  options: { model: Zone, type: object }
  param: { module: dining_room, action: index }
  requirements: { id: \d+ }
  
#dining_room
dining_room_new:
  url: /zone/room/new/:id
  class: sfDoctrineRoute
  options: { model: Zone, type: object }
  param: { module: dining_room, action: new }
  requirements: { zone_id: \d+ }
  
dining_room_create:
  url:     /zone/room/create/:id
  class:   sfDoctrineRoute
  options: { model: Zone, type: object }
  param:   { module: dining_room, action: create, sf_format: html }
  requirements: { sf_method: post, category_id: \d+ }  
  
dining_room_edit:
  url: /zone/room/edit/:id
  class: sfDoctrineRoute
  options: { model: DiningRoom, type: object }
  param: { module: dining_room, action: edit }
  requirements: { id: \d+ }  
  
dining_room_update:
  url:     /zone/room/update/:id.:sf_format
  class:   sfDoctrineRoute
  options: { model: DiningRoom, type: object }
  param:   { module: dining_room, action: update, sf_format: html }
  requirements: { sf_method: put }
  
dining_room_delete:
  url:          /zone/room/:id
  class:        sfDoctrineRoute
  options:      { model: DiningRoom, type: object }
  param:        { module: dining_room, action: delete }
  requirements: { zone_id: \d+, sf_method: delete }

dining_room_detail:
  url:          /zone/room/table/:id
  class:        sfDoctrineRoute
  options:      { model: DiningRoom, type: object }
  param:        { module: dining_table, action: index }
  requirements: { id: \d+ }
  
#dining_table
dining_table_new:
  url: /zone/room/table/new/:id
  class: sfDoctrineRoute
  options: { model: DiningRoom, type: object }
  param: { module: dining_table, action: new }
  requirements: { zone_id: \d+ }
  
dining_table_create:
  url:     /zone/room/table/create/:id
  class:   sfDoctrineRoute
  options: { model: DiningRoom, type: object }
  param:   { module: dining_table, action: create, sf_format: html }
  requirements: { sf_method: post, category_id: \d+ }  
  
dining_table_edit:
  url: /zone/room/table/edit/:id
  class: sfDoctrineRoute
  options: { model: DiningTable, type: object }
  param: { module: dining_table, action: edit }
  requirements: { id: \d+ }  
  
dining_table_update:
  url:     /zone/room/table/update/:id.:sf_format
  class:   sfDoctrineRoute
  options: { model: DiningTable, type: object }
  param:   { module: dining_table, action: update, sf_format: html }
  requirements: { sf_method: put }
  
dining_table_delete:
  url:          /zone/room/table/:id
  class:        sfDoctrineRoute
  options:      { model: DiningTable, type: object }
  param:        { module: dining_table, action: delete }
  requirements: { zone_id: \d+, sf_method: delete }
  
dining_table_ajax:
  url:   /zone/room/table/request/:android_id
  class: sfDoctrineRoute
  options: { model: Tablet, type: object }
  param: { module: dining_table, action: tableForm, sf_format: html }
  
#sf_guard rules
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
        
sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
        
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
  
sf_guard_register:
  url:   /waiter/new
  param: { module: sfGuardAuth, action: register }
  
sf_guard_list:
  url:   /waiter
  param: { module: sfGuardAuth, action: index }

sf_guard_edit:
  url:   /waiter/edit/:id
  class: sfDoctrineRoute
  options: { model: sfGuardUser, type: object }
  param: { module: sfGuardAuth, action: edit }
  requirements: 
    id: \d+

sf_guard_update:
  url:   /waiter/:id
  class: sfDoctrineRoute
  options: { model: sfGuardUser, type: object }
  param: { module: sfGuardAuth, action: update }
  requirements: 
    sf_method: put
    
# Categories rules
category_detail:
  url:  /category/:id
  class: sfDoctrineRoute
  options: { model: Category, type: object }
  param: { module: product, action: index}
  requirements:
    id: \d+
    sf_method: [get]

category:
  class: sfDoctrineRouteCollection
  options: { model: Category }
    
#Products rules  
product:
  class: sfDoctrineRouteCollection
  options: { model: Product }
  
product_new:
  url:     /product/new/:id.:sf_format
  class:   sfDoctrineRoute
  options: { model: Category, type: object }
  param:   { module: product, action: new, sf_format: html }
  requirements: { sf_method: get, category_id: \d+ }
 
product_create:
  url:     /product/:id.:sf_format
  class:   sfDoctrineRoute
  options: { model: Category, type: object }
  param:   { module: product, action: create, sf_format: html }
  requirements: { sf_method: post, category_id: \d+ }
  
product_edit:
  url:     /product/:id/edit.:sf_format
  class:   sfDoctrineRoute
  options: { model: Product, type: object }
  param:   { module: product, action: edit, sf_format: html }
  requirements: { sf_method: get }
 
product_update:
  url:     /product/:id.:sf_format
  class:   sfDoctrineRoute
  options: { model: Product, type: object }
  param:   { module: product, action: update, sf_format: html }
  requirements: { sf_method: put }
    
# Default rules

homepage:
  url:   /
  param: { module: table_order, action: index }

#generic rules
#please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*
