# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing


#table_order

  
table_order:
  class: sfDoctrineRouteCollection
  options: { model: TableOrder, prefix_path: /order }

table_order_ajax:
  url: /order/list.:sf_format
  class: sfDoctrineRoute
  options: { model: TableOrder, type: object }
  param: { module: table_order, action: ajax, sf_format: html }
  requirements: { sf_format:  (?:html|js)}
  
table_order_detail:
  url: /order/detail/:id
  class: sfDoctrineRoute
  options: { model: TableOrder, type: object }
  params: { module: order_product, action: index }
  requirements: { id: \d+ }
  
table_order_close:
  url: /order/close/:id/:all
  class: sfDoctrineRoute
  options: { model: TableOrder, type: object }
  params: { module: table_order, action: close }
  requirements: { id: \d+ }
  
table_order_all:
  url: /order/:all
  class: sfDoctrineRoute
  options: { model: TableOrder, type: object }
  param: { module: table_order, action: index }
#order_product

#zone 
zone:
  class: sfDoctrineRouteCollection
  options: { model: Zone }

zone_detail:
  url:  /zone/room/:id
  class: sfDoctrineRoute
  options: { model: Zone, type: object }
  param: { module: dining_room, action: index }
  requirements: { id: \d+ }
  
#dining_room
dining_room_new:
  url: /zone/room/new/:id
  class: sfDoctrineRoute
  options: { model: Zone, type: object }
  param: { module: dining_room, action: new }
  requirements: { zone_id: \d+ }
  
dining_room_create:
  url:     /zone/room/create/:id
  class:   sfDoctrineRoute
  options: { model: Zone, type: object }
  param:   { module: dining_room, action: create, sf_format: html }
  requirements: { sf_method: post, category_id: \d+ }  
  
dining_room_edit:
  url: /zone/room/edit/:id
  class: sfDoctrineRoute
  options: { model: DiningRoom, type: object }
  param: { module: dining_room, action: edit }
  requirements: { id: \d+ }  
  
dining_room_update:
  url:     /zone/room/update/:id.:sf_format
  class:   sfDoctrineRoute
  options: { model: DiningRoom, type: object }
  param:   { module: dining_room, action: update, sf_format: html }
  requirements: { sf_method: put }
  
dining_room_delete:
  url:          /zone/room/:id
  class:        sfDoctrineRoute
  options:      { model: DiningRoom, type: object }
  param:        { module: dining_room, action: delete }
  requirements: { zone_id: \d+, sf_method: delete }

dining_room_detail:
  url:          /zone/room/table/:id
  class:        sfDoctrineRoute
  options:      { model: DiningRoom, type: object }
  param:        { module: dining_table, action: index }
  requirements: { id: \d+ }
  
#dining_table
dining_table_new:
  url: /zone/room/table/new/:id
  class: sfDoctrineRoute
  options: { model: DiningRoom, type: object }
  param: { module: dining_table, action: new }
  requirements: { zone_id: \d+ }
  
dining_table_create:
  url:     /zone/room/table/create/:id
  class:   sfDoctrineRoute
  options: { model: DiningRoom, type: object }
  param:   { module: dining_table, action: create, sf_format: html }
  requirements: { sf_method: post, category_id: \d+ }  
  
dining_table_edit:
  url: /zone/room/table/edit/:id
  class: sfDoctrineRoute
  options: { model: DiningTable, type: object }
  param: { module: dining_table, action: edit }
  requirements: { id: \d+ }  
  
dining_table_update:
  url:     /zone/room/table/update/:id.:sf_format
  class:   sfDoctrineRoute
  options: { model: DiningTable, type: object }
  param:   { module: dining_table, action: update, sf_format: html }
  requirements: { sf_method: put }
  
dining_table_delete:
  url:          /zone/room/table/:id
  class:        sfDoctrineRoute
  options:      { model: DiningTable, type: object }
  param:        { module: dining_table, action: delete }
  requirements: { zone_id: \d+, sf_method: delete }
  
#sf_guard rules
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
        
sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
        
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
  
# Categories rules
category_detail:
  url:  /category/:id
  class: sfDoctrineRoute
  options: { model: Category, type: object }
  param: { module: product, action: index}
  requirements:
    id: \d+
    sf_method: [get]

category:
  class: sfDoctrineRouteCollection
  options: { model: Category }
    
#Products rules  
product:
  class: sfDoctrineRouteCollection
  options: { model: Product }
  
product_new:
  url:     /product/new/:id.:sf_format
  class:   sfDoctrineRoute
  options: { model: Category, type: object }
  param:   { module: product, action: new, sf_format: html }
  requirements: { sf_method: get, category_id: \d+ }
 
product_create:
  url:     /product/:id.:sf_format
  class:   sfDoctrineRoute
  options: { model: Category, type: object }
  param:   { module: product, action: create, sf_format: html }
  requirements: { sf_method: post, category_id: \d+ }
  
product_edit:
  url:     /product/:id/edit.:sf_format
  class:   sfDoctrineRoute
  options: { model: Product, type: object }
  param:   { module: product, action: edit, sf_format: html }
  requirements: { sf_method: get }
 
product_update:
  url:     /product/:id.:sf_format
  class:   sfDoctrineRoute
  options: { model: Product, type: object }
  param:   { module: product, action: update, sf_format: html }
  requirements: { sf_method: put }
# Default rules

homepage:
  url:   /
  param: { module: category, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
