Zone:
  columns:
    name:               { type: string, notnull: true }
  
DiningRoom:
  columns:
    name:               { type: string, notnull: true }
    zone_id:            { type: integer, notnull: true }
  relations:
    Zone:               { onDelete: CASCADE, local: zone_id }

DiningTable:
  columns:
    name:               { type: string,  notnull: true }
    seats:              { type: integer, notnull: true }
    dining_room_id:     { type: integer, notnull: true }
  relations:
    DiningRoom:         { onDelete: CASCADE, local: dining_room_id }

TableOrder:
  actAs:
    Timestampable:
      updated:          { disabled: true }
  columns:
    is_closed:          { type: boolean, default: false }
    dining_table_id:    { type: integer, notnull: true }
    is_new:             { type: boolean, default: true }
    pay_key:            { type: string, notnull: true }
  relations:
    DiningTable:        { local: dining_table_id }

OrderProduct:
  columns:
    table_order_id:     { type: integer, notnull: true }
    product_id:         { type: integer, notnull: true }
    quantity:           { type: integer, notnull: true }
  relations:
    TableOrder:         { local: table_order_id }
    Product:            { local: product_id }

Product:
  columns:
    name:               { type: string, notnull: true }
    category_id:        { type: integer, notnull: true }
    description:        { type: string }
    price:              { type: decimal, notnull: true }
    available:          { type: boolean, default: true }
  relations:
    Category:           { onDelete: CASCADE, local: category_id }

Category:
  columns:
    name:               { type: string, notnull: true }

Tablet:
  columns:
    android_id:         { type: string, size: 16, primary: true }
    dining_table_id:    { type: integer, notnull: true, unique: true }
    help:               { type: integer, default: 0 }
  relations:
    DiningTable:        { onDelete: CASCADE, local: dining_table_id }

TabletRequest:
  actAs:
    Timestampable:
      updated:          { disabled: true }
  columns:
    android_id:         { type: string, size: 16, primary: true }
    last_check:         { type: timestamp }
    is_new:             { type: boolean, default: true }
    
Menu:
  columns:
    name:               { type: string, notnull: true }
    is_available:       { type: boolean, default: false }

MenuProduct:
  columns:
    product_id:         { type: integer, notnull: true }
    menu_id:            { type: integer, notnull: true }
    is_available:       { type: boolean, default: true }
  relations:
    Product:            { local: product_id, onDelete: CASCADE }
    Menu:               { local: menu_id, onDelete: CASCADE    }